CONFIG_GPIO=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_VID=0x1209
CONFIG_USB_DEVICE_PID=0xC0CA
CONFIG_USB_DEVICE_MANUFACTURER="Jean THOMAS"
CONFIG_USB_DEVICE_PRODUCT="DirtyJTAG"
CONFIG_USB_DEVICE_SN="000000000000000000000000"
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024
CONFIG_LOG=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
