CONFIG_DIRTYJTAG_UNIVERSAL_FRONTEND=n
CONFIG_DIRTYJTAG_LEGACY_FRONTEND=y
CONFIG_DIRTYJTAG_LEGACY_UART_TRANSPORT=y

CONFIG_USB_DEVICE_STACK=n
CONFIG_USB_DEVICE_STACK_NEXT=n
CONFIG_ADC=n
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=n
CONFIG_CONSOLE=n
CONFIG_UART_LINE_CTRL=n
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024
