name: Firmware builds

on:
  push:
    branches: [ master ]
    path-ignore:
      - 'docs/**'
      - 'contrib/**'
  pull_request:
    path-ignore:
      - 'docs/**'
      - 'contrib/**'

jobs:
  default:
    runs-on: ubuntu-24.04
    steps:
    - name: Fetch Sources
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install build dependencies
      run: sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi make
    - name: Build
      run: |
        make -C dirty_jtag BUILD_DIR=build-bluepill
        make -C dirty_jtag BOARD=olimex_stm32_h103/stm32f103xb BUILD_DIR=build-olimex-stm32h103
        make -C dirty_jtag BOARD=stm32_min_dev/stm32f103xb BUILD_DIR=build-stm32-min-dev
